name: pages-build-deployment-apikey

on:
  push:
    branches:
      - main

env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy
      run: |
        echo "Deploying with API key: ${API_KEY}"
        # Your deployment commands here
